# Replace the values in the fields below with your own info so the scraper can send out emails.

# "from" & "username" is the email address that will be sending out the emails. I made a throwaway gmail account for this.
# "password" is the password for the sender account.
# "receiver" is the email address that the sender email account will be sending the email to.
# "smtp server" is the smtp server the sender email account uses. If the sender email is a gmail address you do not need to change this.
# "smtp port" is the port the above smtp server uses. If the sender email is a gmail address you do not need to change this.

from: sender@example.com
username: sender@example.com
password: Sender Password
receiver: receiver@example.com
smtp server: smtp.gmail.com
smtp port: 465

---
# Set the URLs you wish to scrape below with an optional list of words to exclude per URL.
# Any filters you apply on the website are a part of the URL and will apply to the scraper.
# "url" is as you would guess the URL you want to scrape.

# You can add as many URLs as you wish to scrape.

# Example of Winnipeg Free Press
- url: https://homes.winnipegfreepress.com/homes-for-sale/min-price-100000/max-price-1000000/min-bedrooms-2/min-bathrooms-2/city-Winnipeg

# Example of Rew
- url: https://www.rew.ca/properties/areas/winnipeg-mb?list_price_from=200000&list_price_to=1000000&only_open_house=0&only_virtual_tour=0